import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fff0fb',
  },
  background: {
    flex: 1,
  },
  page: {
    width: '100%',
    maxWidth: 620,
    alignSelf: 'center',
    padding: 20,
    paddingBottom: 48,
    gap: 14,
  },
  mainStack: {
    gap: 14,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  fullHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  titleBox: {
    flex: 1,
  },
  logo: {
    color: '#dfe8f4',
    fontWeight: '900',
    letterSpacing: 2,
    textShadowColor: '#35124d',
    textShadowRadius: 0,
  },
  dateText: {
    color: '#6e7887',
    fontSize: 15,
    fontWeight: '900',
    textShadowColor: '#ffffff',
    textShadowOffset: { width: 0, height: -1 },
    textShadowRadius: 1,
  },
  iconButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  iconButtonText: {
    color: '#657180',
    fontSize: 24,
    fontWeight: '900',
  },
  panel: {
    padding: 14,
    gap: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(36,242,255,0.28)',
  },
  panelTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  panelTitleText: {
    color: '#25232a',
    fontSize: 15,
    fontWeight: '900',
  },
  smallNote: {
    color: '#6e7887',
    fontSize: 12,
    fontWeight: '900',
  },
  moneyFields: {
    flexDirection: 'row',
    gap: 10,
  },
  moneyField: {
    flex: 1,
    gap: 8,
  },
  inputLabel: {
    color: '#6e7887',
    fontSize: 13,
    fontWeight: '900',
  },
  moneyInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 50,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: '#fff8e6',
  },
  moneyYen: {
    fontSize: 18,
    fontWeight: '900',
  },
  moneyInput: {
    flex: 1,
    color: '#25232a',
    fontSize: 20,
    fontWeight: '900',
  },
  metrics: {
    flexDirection: 'row',
    gap: 8,
  },
  metric: {
    flex: 1,
    padding: 10,
    gap: 4,
    borderRadius: 10,
    backgroundColor: '#ffffff',
  },
  metricLabel: {
    color: '#6e7887',
    fontSize: 11,
    fontWeight: '900',
  },
  metricValue: {
    color: '#25232a',
    fontSize: 14,
    fontWeight: '900',
  },
  amountBox: {
    height: 78,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: '#fff8e6',
  },
  yenMark: {
    fontSize: 26,
    fontWeight: '900',
  },
  amountInput: {
    flex: 1,
    color: '#25232a',
    textAlign: 'center',
    fontSize: 46,
    fontWeight: '900',
  },
  genreGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  choiceButton: {
    flexGrow: 1,
    minWidth: 78,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(36,242,255,0.22)',
    backgroundColor: 'rgba(255,255,255,0.94)',
  },
  choiceActive: {
    borderColor: 'rgba(255,41,148,0.58)',
    backgroundColor: 'rgba(255,41,148,0.13)',
  },
  choiceIncome: {
    borderColor: 'rgba(18,148,85,0.72)',
    backgroundColor: 'rgba(18,148,85,0.16)',
  },
  choiceText: {
    color: '#657180',
    fontSize: 13,
    fontWeight: '900',
  },
  primaryButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.86)',
  },
  primaryButtonText: {
    color: '#657180',
    fontSize: 16,
    fontWeight: '900',
  },
  monthNav: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  monthLabel: {
    flex: 1,
    color: '#25232a',
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '900',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
  },
  dow: {
    width: '13.4%',
    color: '#6e7887',
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '900',
  },
  dayBlank: {
    width: '13.4%',
    height: 38,
  },
  dayButton: {
    width: '13.4%',
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  daySelected: {
    backgroundColor: 'rgba(36,242,255,0.34)',
  },
  dayText: {
    color: '#657180',
    fontSize: 13,
    fontWeight: '900',
  },
  dayDot: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: 4,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: '#efb33d',
  },
  entryRow: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#ffffff',
  },
  entryText: {
    flex: 1,
    color: '#25232a',
    fontSize: 13,
    fontWeight: '900',
  },
  entrySub: {
    color: '#6e7887',
    fontSize: 11,
    fontWeight: '900',
  },
  entryAmount: {
    fontSize: 13,
    fontWeight: '900',
  },
  positive: {
    color: '#129455',
  },
  negative: {
    color: '#ea5048',
  },
  deleteText: {
    color: '#ea5048',
    fontSize: 12,
    fontWeight: '900',
  },
  segmented: {
    flexDirection: 'row',
    gap: 8,
  },
  shareCard: {
    aspectRatio: 1,
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'space-between',
    padding: 18,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
  },
  cardStripe: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 9,
  },
  comicMark: {
    position: 'absolute',
    top: 42,
    right: 22,
    fontSize: 64,
    fontWeight: '900',
    transform: [{ rotate: '-12deg' }],
  },
  sparkLeft: {
    position: 'absolute',
    bottom: 48,
    left: 24,
    color: 'rgba(255,41,148,0.28)',
    fontSize: 42,
    fontWeight: '900',
    transform: [{ rotate: '14deg' }],
  },
  sparkRight: {
    position: 'absolute',
    right: 28,
    bottom: 92,
    color: 'rgba(36,242,255,0.48)',
    fontSize: 22,
    fontWeight: '900',
    transform: [{ rotate: '8deg' }],
  },
  reportTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  periodText: {
    color: '#6e7887',
    fontSize: 12,
    fontWeight: '900',
  },
  reportMain: {
    gap: 9,
  },
  sticker: {
    alignSelf: 'flex-start',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.72)',
    fontSize: 13,
    fontWeight: '900',
  },
  quote: {
    color: '#6f7a89',
    fontSize: 36,
    fontWeight: '900',
    lineHeight: 38,
    textShadowColor: '#ffffff',
    textShadowOffset: { width: 0, height: -1 },
    textShadowRadius: 1,
  },
  reportTitle: {
    color: '#657180',
    fontSize: 19,
    fontWeight: '900',
  },
  reportNumber: {
    fontSize: 30,
    fontWeight: '900',
  },
  reportCopy: {
    color: 'rgba(31,31,29,0.72)',
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 18,
  },
  hashText: {
    color: 'rgba(31,31,29,0.66)',
    fontSize: 12,
    fontWeight: '900',
  },
  shareGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  shareButton: {
    flex: 1,
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  shareButtonText: {
    color: '#657180',
    fontSize: 12,
    fontWeight: '900',
  },
  helperText: {
    color: '#6e7887',
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '800',
  },
});
